# Generated by Django 3.1.7 on 2021-03-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='', max_length=60, unique=True),
        ),
    ]
