# Generated by Django 3.1.7 on 2021-03-31 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_remove_task_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 15, 13, 13, 289585)),
        ),
    ]
