# Generated by Django 3.1.7 on 2021-03-25 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20210325_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='done_date',
        ),
    ]
