# Generated by Django 3.1.7 on 2021-03-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_auto_20210325_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
