# Generated by Django 3.1.7 on 2021-03-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20210322_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
    ]
