# Generated by Django 3.1.7 on 2021-03-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20210325_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
