# Generated by Django 3.1.7 on 2021-03-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_task_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='done',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='task_text',
            field=models.TextField(default=1, max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
