# Generated by Django 3.1.7 on 2021-04-05 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_auto_20210401_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='frends',
            field=models.ManyToManyField(blank=True, related_name='_user_frends_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InviteKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=25)),
                ('friend_id', models.IntegerField(blank=True)),
                ('invitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
