# Generated by Django 3.1.7 on 2021-04-06 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0011_auto_20210405_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitekey',
            name='friend_id',
        ),
        migrations.AddField(
            model_name='invitekey',
            name='friend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
