# Generated by Django 3.1.7 on 2021-04-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0012_auto_20210406_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitekey',
            name='key',
            field=models.SlugField(unique=True),
        ),
    ]
