# Generated by Django 3.1.7 on 2021-04-06 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0013_auto_20210406_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitekey',
            name='friend',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
